services:
  nbpplnexchangeratesapi:
    image: nbpplnexchangeratesapi
    build:
      context: .
      dockerfile: src/NbpPlnExchangeRates.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DatabaseOptions__DatabaseConnectionString: "Server=mssql; Database=NbpPlnExchangeRates;User ID=SA; Password=<)M=!#yuYC.{30v£07`N$;TrustServerCertificate=true"
      DatabaseOptions__EnablesSensitiveDataLogging: false
      DatabaseOptions__EnableDetailedErrors: false
      DatabaseOptions__CommandTimeout: 10
    depends_on:
      - mssql
      
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "<)M=!#yuYC.{30v£07`N$"
    volumes:
      - ./:/app
